version: '3.3'
services:
    mongo:
        ports:
            - '27017:27017'
        container_name: rick-morty-mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=rick-morty-secret
        image: mongo